
---
all:
  children:
    ios:
      hosts:
        r1:
          ansible_host: 192.168.56.20
        r2:
          ansible_host: 192.168.56.21
        r3:
          ansible_host: 192.168.56.22
        r4:
          ansible_host: 192.168.56.23
        r5:
          ansible_host: 192.168.56.24
