$ANSIBLE_VAULT;1.1;AES256
38326432323934336536393931663734626331326631313133663535303330663536386636383635
6532343239343633386132353230373663343037326637610a396166346266383565333930616566
64316639336433653930633132653430313531613037306562363365653864366464373933666263
3635616532396634620a363938363962323862323037646233386462333633336437356265353037
66656334353462373061313730353665653133643035383136646136323465373038623765336563
32383933383165653434626231363863383739616538333331653337613766346439656265633965
38326363623439313262306166343333623237633336323861643637376263363639393064373138
39663231636263316562343539366532353933653562333530643564333665326137616261313838
37633361626236386466396234386638633965333339623165313365373661626136316166346464
64633030323966303136623330303538396666323837303631626337656666363033663864316665
31353739656366393334373039636461316239613636353733376563323334633431333430353932
33373934323139303539303035353335356534333763393135666365356466626661323437613736
32363465653261393230353934353238653033393466363636313735643166636162363732346361
63643234313830346562633465393563313563626238393031393035613565616239313561353462
336165623061353235326436616361643935
